### ISSUE TITLE
Action throws a TypeError

### ISSUE THREAD

**Issue by exil0867** [Jaid/action-sync-node-meta#30]
I am getting the following error:
```
Error: TypeError: e.request is not a function
      at W.requestGithubApi (/home/runner/work/_actions/jaid/action-sync-node-meta/v2.0.0/build/index.js:6:7918[39](https://github.com/EXILL-SUARL/batch-blur-images/runs/7915332768?check_suite_focus=true#step:3:42))
      at W.applyGithubUpdate (/home/runner/work/_actions/jaid/action-sync-node-meta/v2.0.0/build/index.js:6:793695)
      at /home/runner/work/_actions/jaid/action-sync-node-meta/v2.0.0/build/index.js:6:795432
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  API endpoint: PUT /repos/:owner/:repo/topics
  API options: owner, repo, names
Error: jaid/action-sync-node-meta threw an Error
Error: Error: Syncing failed
    at /home/runner/work/_actions/jaid/action-sync-node-meta/v2.0.0/build/index.js:6:797172
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Link to the logs: https://github.com/EXILL-SUARL/batch-blur-images/runs/7915332768?check_suite_focus=true#step:3:17

**Comment by iloveitaly** [comment]
I'm getting this as well

**Comment by iloveitaly** [comment]
Looks like this is the source of the issue: https://github.com/Jaid/action-sync-node-meta/blob/6eb235046d1bcfe3460260051044ca3bb455c5eb/src/lib/Property.js#L153

probably a dependency issue?

**Comment by kezzyhko** [comment]
I had the same issue. Downgraded to `1.4.0` and it works perfectly.

If you have the same issue and also have `actions/setup-node` in your workflow, you might try downgrading the node version (?)
