### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by moltar** [Jaid/action-sync-node-meta#9]
I get the following errors:

```
action-sync-node-meta v1.3.1
Syncing direction: package.json → GitHub repository info
 Description             failed 
  pkg.description: 'Foo'
  repository.description: 'Bar'
  ##[error]HttpError: Resource not accessible by integration
      at /home/runner/work/_actions/jaid/action-sync-node-meta/v1.4.0/build/index.js:6:219539
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async q.requestGithubApi (/home/runner/work/_actions/jaid/action-sync-node-meta/v1.4.0/build/index.js:6:1057993)
      at async q.applyGithubUpdate (/home/runner/work/_actions/jaid/action-sync-node-meta/v1.4.0/build/index.js:6:1058148)
      at async /home/runner/work/_actions/jaid/action-sync-node-meta/v1.4.0/build/index.js:6:1060873
  API endpoint: PATCH /repos/:owner/:repo
  API options: owner, repo, description
 Homepage              disabled 
 Keywords                failed 
##[error]jaid/action-sync-node-meta threw an Error
##[error]Error: Syncing failed
    at /home/runner/work/_actions/jaid/action-sync-node-meta/v1.4.0/build/index.js:6:1062658
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Any ideas?

Thanks!

**Comment by Jaid** [comment]
If you choose “overwrite-github” as the syncing direction, you need to pass a token with the correct scope. Otherwise the action does not have the permission to make changes to your repository's metadata.

I added a tutorial with screenshots to the readme to make this setup easier.
